theme: minima
title: Coumputational  Linguist
author: Michael Bateman
email: michael.bateman.com@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog site for NLP and Data Science

# social linksWrite an awesome description for your new site here. You can edit this
7
  line in _config.yml. It will appear in your document head meta (for
8
  Google search results) and in your feed.xml site description.
twitter_username: m_r_bateman
github_username:  mbateman

show_excerpts: true # set to false to remove excerpts on the homepage
